# Generated by Django 5.1 on 2024-08-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviemagic_app', '0005_review_reviewer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='number_of_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
